version: "3.5"

services:
  cli:
    container_name: matthewporuben-cli
    build: ./app/docker
    volumes:
      - ./app:/app
      - ./public:/app/src/public
      - ./content:/app/src/content
  dev:
    container_name: matthewporuben-dev
    build: ./app/docker
    command: npm run dev
    ports:
      - 3000:3000
    volumes:
      - ./app:/app
      - ./public:/app/src/public
      - ./content:/app/src/content

