name: Deploy to production

on:
  push:
    branches: [ master ]

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: npm run gen
