name: Deploy to production

on:
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: CI
        run: npm ci
      - name: Generating static assets
        run: npm run gen
      - name: Upload build
        run: echo ${{ secrets.WS_PASSWORD }} | scp -P 26776 ./dist uid1140413@shellserver-2.websupport.sk:matthewporuben.com/sub/staging
        with:
          ssh-private-key: ${{ secrets.SSH }}

