
name: Deploy to production
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: CI
        run: npm ci

      - name: Generating static assets
        run: npm run gen

      - name: Upload build
        run: npm run gen

#      - name: Move deployed files to prod
#        uses: appleboy/ssh-action@master
#        with:
#          host: shellserver-2.websupport.sk
#          username: uid1140413
#          password: ${{ secrets.WS_PASSWORD }}
#          port: 26776
#          script: ls matthewporuben.com/repo/dist






