name: Deploy to production

on:
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: CI
        run: npm ci
      - name: Generating static assets
        run: npm run gen
      - name: Zip builded assets
        run: zip -r dist.zip ./dist
