name: Deploy to production

on:
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: webfactory/ssh-agent@v0.6.0
        with:
          ssh-private-key: ${{ secrets.SSH }}

      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: CI
        run: npm ci

      - name: Generating static assets
        run: npm run gen

      - name: Upload build
        uses: appleboy/scp-action@master
        with:
          host: shellserver-2.websupport.sk
          username: uid1140413
          password: ${{ secrets.WS_PASSWORD }}
          port: 26776
          rm: true
          source: "./dist/*"
          target: "/home/matthewporuben.com/repo"

      - name: Move deployed files to prod
        uses: appleboy/ssh-action@master
        with:
          host: shellserver-2.websupport.sk
          username: uid1140413
          password: ${{ secrets.WS_PASSWORD }}
          port: 26776
          script: ls matthewporuben.com/repo/dist





