name: Deploy to production

on:
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.6.0
        with:
          ssh-private-key: ${{ secrets.SSH }}
      - name: CI
        run: npm ci
      - name: Generating static assets
        run: npm run gen
#      - name: Upload build
#        run: echo ${{ secrets.WS_PASSWORD }} | scp -P 26776 ./dist uid1140413@shellserver-2.websupport.sk:matthewporuben.com/sub/staging
      - name: Upload build
        uses: appleboy/scp-action@master
        with:
           host: shellserver-2.websupport.sk
           username: uid1140413
           password: ${{ secrets.WS_PASSWORD }}
           port: 26776
           source: "./dist/"
           target: "matthewporuben.com/sub/staging"


